# Generated by Django 3.1.2 on 2021-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
